spring:
  application:
    name: bikehub
  config:
    import: optional:classpath:application-secret.properties
  datasource:
    url: jdbc:mysql://crossover.proxy.rlwy.net:36525/railway
    username: root
    password: ArUHrWJsaZXDghwQNPwQbcTmhcnUXvhD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB

jwt:
  signerKey: "a4aec8aa399e085aa2c40ae8106d7bb6c55c825a6149916bfcc9920e441d05c2"
  valid-duration: 3600
  refreshable-duration: 36000

com:
  bikehub:
    sendgrid:
      api-key:  ${SENDGRID_API_KEY}
      from-email: ${SENDGRID_FROM_EMAIL}
      from-name: ${SENDGRID_FROM_NAME}
    googlevision:
      base-url: https://vision.googleapis.com/v1/images:annotate
      api-key: ${GOOGLE_VISION_API_KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


